/*******************************************************************************
 * JMMC project
 *
 * "@(#) $Id: TargetModelForm.java,v 1.3 2010-02-08 17:00:47 bourgesl Exp $"
 *
 * History
 * -------
 * $Log: not supported by cvs2svn $
 * Revision 1.2  2010/02/01 09:43:49  bourgesl
 * header + comments
 *
 */
package fr.jmmc.aspro.gui;

/**
 * This class represents the target model editor ...
 * @author bourgesl
 */
public class TargetModelForm extends javax.swing.JPanel {

  /** default serial UID for Serializable interface */
  private static final long serialVersionUID = 1;
  /** Class Name */
  private static final String className_ = "fr.jmmc.aspro.gui.TargetModelForm";
  /** Class logger */
  private static java.util.logging.Logger logger = java.util.logging.Logger.getLogger(
          className_);

    /** Creates new form TargetModelForm */
    public TargetModelForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel4 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    modelList = new javax.swing.JList();
    addModelButton = new javax.swing.JButton();
    modelTypeComboBox = new javax.swing.JComboBox();
    removeModelButton = new javax.swing.JButton();
    jPanel5 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jTextField2 = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();

    setBorder(javax.swing.BorderFactory.createTitledBorder("Target"));
    setLayout(new java.awt.GridBagLayout());

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Model list"));
    jPanel4.setMinimumSize(new java.awt.Dimension(300, 100));
    jPanel4.setPreferredSize(new java.awt.Dimension(300, 100));
    jPanel4.setLayout(new java.awt.GridBagLayout());

    jScrollPane2.setMinimumSize(new java.awt.Dimension(22, 82));
    jScrollPane2.setPreferredSize(new java.awt.Dimension(260, 82));

    modelList.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        modelListMouseClicked(evt);
      }
    });
    modelList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        modelListValueChanged(evt);
      }
    });
    jScrollPane2.setViewportView(modelList);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    jPanel4.add(jScrollPane2, gridBagConstraints);

    addModelButton.setText("Add model");
    addModelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addModelButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    jPanel4.add(addModelButton, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    jPanel4.add(modelTypeComboBox, gridBagConstraints);

    removeModelButton.setText("Remove");
    removeModelButton.setEnabled(false);
    removeModelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        removeModelButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    jPanel4.add(removeModelButton, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weighty = 0.1;
    add(jPanel4, gridBagConstraints);

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));
    jPanel5.setMinimumSize(new java.awt.Dimension(300, 100));
    jPanel5.setPreferredSize(new java.awt.Dimension(300, 100));
    jPanel5.setLayout(new java.awt.BorderLayout());

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jTable1.setMinimumSize(new java.awt.Dimension(200, 150));
    jTable1.setPreferredSize(new java.awt.Dimension(200, 150));
    jScrollPane1.setViewportView(jTable1);

    jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.weighty = 0.2;
    add(jPanel5, gridBagConstraints);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));
    jPanel1.setMinimumSize(new java.awt.Dimension(300, 80));
    jPanel1.setPreferredSize(new java.awt.Dimension(300, 80));
    jPanel1.setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("RA (H:M:S)");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel1.add(jLabel1, gridBagConstraints);

    jLabel2.setText("DEC (D:M:S)");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel1.add(jLabel2, gridBagConstraints);

    jTextField1.setEditable(false);
    jTextField1.setText("RA");
    jTextField1.setMinimumSize(new java.awt.Dimension(100, 19));
    jTextField1.setPreferredSize(new java.awt.Dimension(100, 19));
    jTextField1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField1ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel1.add(jTextField1, gridBagConstraints);

    jTextField2.setEditable(false);
    jTextField2.setText("DEC");
    jTextField2.setMinimumSize(new java.awt.Dimension(100, 19));
    jTextField2.setPreferredSize(new java.awt.Dimension(100, 19));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel1.add(jTextField2, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weighty = 0.2;
    add(jPanel1, gridBagConstraints);

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("UV Map"));
    jPanel2.setMinimumSize(new java.awt.Dimension(300, 300));
    jPanel2.setPreferredSize(new java.awt.Dimension(300, 300));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    add(jPanel2, gridBagConstraints);

    jButton1.setText("refresh UV map");
    jPanel3.add(jButton1);

    jButton2.setText("OK");
    jPanel3.add(jButton2);

    jButton3.setText("Cancel");
    jPanel3.add(jButton3);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    add(jPanel3, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

    private void modelListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modelListMouseClicked
/*
      if (evt.getClickCount() == 2) {
        rootSettingsModel.setSelectionPath(
                new TreePath(new Object[]{
          rootSettingsModel,
          rootSettingsModel.getRootSettings().getTargets(),
          current,
          modelList.getSelectedValue() } ));
      }
 */
}//GEN-LAST:event_modelListMouseClicked

    private void modelListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_modelListValueChanged

      if (modelList.getSelectedIndex() != -1) {
        removeModelButton.setEnabled(true);
      } else {
        removeModelButton.setEnabled(false);
      }
    }//GEN-LAST:event_modelListValueChanged

    private void addModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModelButtonActionPerformed
   /*   logger.entering("" + this.getClass(), "addModelButtonActionPerformed");

      try {
        // Construct a new copy
        Model        selectedModel = (Model) modelTypeComboBox.getSelectedItem();
        Model        m;
        // Clone selected Model (this code could have been moved into model???
        StringWriter writer   = new StringWriter();
        UtilsClass.marshal(selectedModel,writer);
        StringReader reader = new StringReader(writer.toString());
        m = (Model)Model.unmarshal(reader);
        rootSettingsModel.addModel(current, m);
        updateModels();
        plotModelImagePanel.show(rootSettingsModel, current);
        plotChi2Panel.show(rootSettingsModel, current);
      } catch (Exception e) {
        // this occurs when add button is pressed without selection
        logger.warning("No model selected");
      }
    */
}//GEN-LAST:event_addModelButtonActionPerformed

    private void removeModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeModelButtonActionPerformed
 /*     logger.entering("" + this.getClass(), "removeModelButtonActionPerformed");
      Object[] values = modelList.getSelectedValues();
      for (int i = 0; i < values.length; i++) {
        Object object = values[i];
        rootSettingsModel.removeModel(current, (Model)object);
        updateModels();
      }
      removeModelButton.setEnabled(false);
      plotModelImagePanel.show(rootSettingsModel, current);
      plotChi2Panel.show(rootSettingsModel, current);
  */
}//GEN-LAST:event_removeModelButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addModelButton;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable jTable1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JList modelList;
  private javax.swing.JComboBox modelTypeComboBox;
  private javax.swing.JButton removeModelButton;
  // End of variables declaration//GEN-END:variables

}
