//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.14 at 05:35:45 PM CEST 
//


package fr.jmmc.aspro.model.oi;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpectralBand.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SpectralBand">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="V"/>
 *     &lt;enumeration value="R"/>
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="J"/>
 *     &lt;enumeration value="H"/>
 *     &lt;enumeration value="K"/>
 *     &lt;enumeration value="N"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SpectralBand")
@XmlEnum
public enum SpectralBand {


    /**
     * V band
     * 
     */
    V,

    /**
     * R band
     * 
     */
    R,

    /**
     * I band
     * 
     */
    I,

    /**
     * J band
     * 
     */
    J,

    /**
     * H band
     * 
     */
    H,

    /**
     * K band
     * 
     */
    K,

    /**
     * N band
     * 
     */
    N;

    public String value() {
        return name();
    }

    public static SpectralBand fromValue(String v) {
        return valueOf(v);
    }

}
