//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.14 at 05:35:45 PM CEST 
//


package fr.jmmc.aspro.model.oi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import fr.jmmc.aspro.model.OIBase;


/**
 * 
 *         This type describes a target
 *       
 * 
 * <p>Java class for Target complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Target">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RA" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="DEC" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="EQUINOX" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Target", propOrder = {
    "name",
    "ra",
    "dec",
    "equinox"
})
public class Target
    extends OIBase
{

    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "RA")
    protected double ra;
    @XmlElement(name = "DEC")
    protected double dec;
    @XmlElement(name = "EQUINOX")
    protected float equinox;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the ra property.
     * 
     */
    public double getRA() {
        return ra;
    }

    /**
     * Sets the value of the ra property.
     * 
     */
    public void setRA(double value) {
        this.ra = value;
    }

    /**
     * Gets the value of the dec property.
     * 
     */
    public double getDEC() {
        return dec;
    }

    /**
     * Sets the value of the dec property.
     * 
     */
    public void setDEC(double value) {
        this.dec = value;
    }

    /**
     * Gets the value of the equinox property.
     * 
     */
    public float getEQUINOX() {
        return equinox;
    }

    /**
     * Sets the value of the equinox property.
     * 
     */
    public void setEQUINOX(float value) {
        this.equinox = value;
    }

}
